version: '3.9'

networks:
  my-network:
    driver: bridge

services:
  apache:
    image: httpd:latest
    container_name: my-apache-app
    restart: unless-stopped
    networks:
      - my-network
    ports:
    - '80:80'
    volumes:
    - ./website:/usr/local/apache2/htdocs
